services:
  base_container:
    environment:
      - TZ=Europe/Moscow

  base_redis:
    image: redis:latest
    restart: on-failure
    extends:
      file: templates.yml
      service: base_container
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  base_postgres:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db
    extends:
      file: templates.yml
      service: base_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 20s